spring:
  datasource:
    # localhost:5432는 내 컴퓨터, cider_db는 아까 pgAdmin에서 만든 이름
    url: jdbc:postgresql://localhost:5432/cider_db
    username: postgres                             # 기본 계정명
    password: sw0202                               # 비밀번호
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # update: 엔티티(User 클래스 등)를 보고 테이블을 자동으로 만들어줌
      ddl-auto: update
    show-sql: true        # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        format_sql: true  # SQL을 보기 좋게 출력
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      # 병부님 gpt api-key
      api-key: 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

jwt:
  # 보안을 위해 실제 서비스에서는 환경변수로 관리해야함
  secret: c2lkZXItcHJvamVjdC1zZWNyZXQta2V5LXZlcnktbG9uZy1hbmQtc2FmZS1zdHJpbmctMTIzNDU2Nzg5MC1hYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5eg==
  expiration: 3600000 # 1시간 (밀리초 단위)

